apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: nginx-deployment
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 100
behavior:
      scaleDown:
        stabilizationWindowSeconds: 600
        policies:
          - type: Pods
            value: 1
            periodSeconds: 100
      scaleUp:
        stabilizationWindowSeconds: 10
        policies:
          - type: Pods
            value: 1
            periodSeconds: 5
